mode: train
model:
  name: retinaface
  helper: RetinaFaceHelper
  helper_kwarg:
    image_ann: data/retinaface_img_ann.npy
    in_hw: 
      - 240
      - 320
    anchor_widths: 
      - - 10
        - 16
        - 24
      - - 32
        - 48
      - - 64
        - 96
      - - 128
        - 192
        - 256
    anchor_steps:
      - 8
      - 16
      - 32
      - 64
    pos_thresh: 0.35
    variances:
      - 0.1
      - 0.2
  network: retinaface_slim
  network_kwarg:
    input_shape:
      - null
      - null
      - 3
    num_classes: 2
  loss: RetinaFaceLoss
  loss_kwarg:
    loc_weight: 1
    landm_weight: 2
    conf_weight: 1
    negpos_ratio: 7
train:
  graph_optimizer: true
  graph_optimizer_kwarg: 
    layout_optimizer: true
    remapping: true
    shape_optimization: true
    loop_optimization: true
    constant_folding: true
    function_optimization: true
    scoped_allocator_optimization: true
    layout_optimizer: true
  augmenter: true
  batch_size: 32
  pre_ckpt: null
  rand_seed: 10101
  epochs: 250
  log_dir: log
  sub_log_dir: default_retinaface_slim_exp
  debug: false
  verbose: 1
  vali_step_factor: 0.5
  optimizer: Adam
  optimizer_kwarg:
    learning_rate: 0.0001
    beta_1: 0.9
    beta_2: 0.999
    amsgrad: false
  Lookahead: true
  Lookahead_kwarg:
    k: 5
    alpha: 0.5
  callbacks:
    # - name: EarlyStopping
    #   kwarg:
    #     monitor: val_loss
    #     min_delta: 0
    #     patience: 4
    #     verbose: 0
    #     mode: auto
    #     baseline: null
    #     restore_best_weights: false
    - name: ModelCheckpoint
      kwarg:
        monitor: val_loss
        verbose: 0
        save_best_only: true
        save_weights_only: false
        mode: auto
        save_freq: epoch
        load_weights_on_restart: false
    - name: TerminateOnNaN
      kwarg: null
    # - name: MultiScaleTrain
    #   kwarg:
    #     interval: 50
    #     scale_range: [-3, 5]
    - name: StepLR
      kwarg:
        steps: [ 20  ,  100 ]
        rates: [0.0001,0.001]
prune:
  is_prune: false
  init_sparsity: 0.5
  final_sparsity: 0.9
  end_epoch: 5
  frequency: 100
inference:
  infer_fn: retinaface_infer
  infer_fn_kwarg:
    obj_thresh: 0.6
    nms_thresh: 0.5
evaluate:
  eval_fn: null