mode: train
model:
  name: yoloalign
  helper: YOLOAlignHelper
  helper_kwarg:
    image_ann: data/celeba_img_ann.npy
    class_num: 1
    anchors: data/celeba_anchor.npy
    landmark_num: 5
    in_hw:
      - 224
      - 320
    out_hw:
      - - 7
        - 10
      - - 14
        - 20
    validation_split: 0.3
  network: yoloalgin_mbv1_k210
  network_kwarg:
    input_shape:
    - 224
    - 320
    - 3
    anchor_num: 3
    class_num: 1
    landmark_num: 5
    alpha: 0.75
  loss: YOLOAlign_Loss
  loss_kwarg:
    iou_thresh: 0.5
    obj_weight: 1
    noobj_weight: 1
    xy_weight: 2
    wh_weight: 3
    landmark_weight: 2
train:
  graph_optimizer: true
  graph_optimizer_kwarg: 
    layout_optimizer: true
    remapping: true
    shape_optimization: true
    loop_optimization: true
    constant_folding: true
    function_optimization: true
    scoped_allocator_optimization: true
    layout_optimizer: true
  augmenter: false
  batch_size: 16
  pre_ckpt: null
  rand_seed: 10101
  epochs: 10
  log_dir: log
  sub_log_dir: null
  debug: false
  verbose: 1
  vali_step_factor: 0.5
  optimizer: RAdam
  optimizer_kwarg:
    lr: 0.0001
    beta_1: 0.9
    beta_2: 0.999
    epsilon: null
    decay: 0.0
  Lookahead: true
  Lookahead_kwarg:
    k: 5
    alpha: 0.5
  callbacks:
    - name: EarlyStopping
      kwarg:
        monitor: val_loss
        min_delta: 0
        patience: 4
        verbose: 0
        mode: auto
        baseline: null
        restore_best_weights: false
    - name: ModelCheckpoint
      kwarg:
        monitor: val_loss
        verbose: 0
        save_best_only: true
        save_weights_only: false
        mode: auto
        save_freq: epoch
        load_weights_on_restart: false
    - name: TerminateOnNaN
      kwarg: null
prune:
  is_prune: false
  init_sparsity: 0.5
  final_sparsity: 0.9
  end_epoch: 5
  frequency: 100
inference:
  infer_fn: yoloalgin_infer
  infer_fn_kwarg:
    obj_thresh: 0.7
    iou_thresh: 0.3
