mode: train
model:
  name: pfld
  helper: LandmarkHelper
  helper_kwarg:
    image_ann: data/wflw_img_ann.npy
    in_hw:
      - 112
      - 112
    landmark_num: 98
    attribute_num: 6
    validation_split: 0.1
  network: pfld
  network_kwarg:
    landmark_num: 98
    alpha: 1.
    weight_decay: 0.00005
  loss: landmark_loss
  loss_kwarg:
    landmark_weight: 1.
    eular_weight: 1.
train:
  augmenter: false
  batch_size: 32
  pre_ckpt: null
  rand_seed: 10101
  epochs: 10
  log_dir: log
  debug: false
  verbose: 1
  vali_step_factor: 0.5
  optimizer: RAdam
  optimizer_kwarg:
    lr: 0.001
    beta_1: 0.9
    beta_2: 0.999
    epsilon: null
    decay: 0.0
  Lookahead: true
  Lookahead_kwarg:
    k: 5
    alpha: 0.5
prune:
  is_prune: false
  init_sparsity: 0.5
  final_sparsity: 0.9
  end_epoch: 5
  frequency: 100
