UPDATE_AUGMENTER_STATE: &UPDATE_AUGMENTER_STATE true

mode: train
model:
  name: fixmatchaudio
  helper: DCASETask5FixMatchSSLHelper
  helper_kwarg:
    data_ann: data/dcasetask5_ann_list.npy
    in_hw:
      - 40
      - 501
    nclasses: 9
    unlabel_dataset_ratio: 3 # Unlabeled batch size ratio.
    augment_kwargs:
      name: ctaugment
      kwarg: 
        num_layers: 2
        confidence_threshold: 0.85
        decay: 0.99
        epsilon: 0.001
        prob_to_apply: null
        num_levels: 10
  network: dcasetask5basemodel
  network_kwarg:
    input_shape:
      - 40
      - 501
      - 1
    nclasses: 9
    softmax: false
train:
  graph_optimizer: true
  graph_optimizer_kwarg: 
    layout_optimizer: true
    remapping: true
    shape_optimization: true
    loop_optimization: true
    constant_folding: true
    function_optimization: true
    scoped_allocator_optimization: true
    layout_optimizer: true
  augmenter: true
  batch_size: 16
  pre_ckpt: null
  rand_seed: 10101
  epochs: 50
  steps_per_run: 30
  log_dir: log
  sub_log_dir: default_dcasetask5_fixmatch_ctaug_exp
  trainloop: Task5FixMatchSslLoop
  trainloop_kwarg:
    update_augmenter_state: *UPDATE_AUGMENTER_STATE
    hparams: 
      fixmatch: 
        wu: 1.0 # Pseudo label loss weight
        confidence: 0.7 # Confidence threshold.
  optimizer: Adam
  optimizer_kwarg:
    learning_rate: 0.001
    beta_1: 0.9
    beta_2: 0.999
    amsgrad: false
  callbacks:
    - name: EarlyStopping
      kwarg:
        monitor: val/acc
        min_delta: 0
        patience: 5
        verbose: 0
        mode: max
        baseline: null
        restore_best_weights: false
    - name: ModelCheckpoint
      kwarg:
        monitor: val/acc
        verbose: 0
        save_best_only: true
        save_weights_only: false
        mode: max
        save_freq: epoch
        load_weights_on_restart: false
    # - name: StepLR
    #   kwarg:
    #     steps: [ 10  ,  20    ,  30   ]
    #     rates: [0.0001, 0.0004,  0.0005]
    - name: AugmenterStateSync
      kwarg: 
        update_augmenter_state: *UPDATE_AUGMENTER_STATE
    - name: ScheduleLR    
      kwarg:
       base_lr: 0.001
       use_warmup: true
       warmup_epochs: 10
       decay_rate: 0.5
       decay_epochs: 10
        
    