mode: train
model:
  name: yolo
  network: yolo_mobilev2
  depth_multiplier: 0.75
  input_hw:
  - 224
  - 320
  output_hw:
  - - 7
    - 10
  - - 14
    - 20
  class_num: 20
  landmark_num: 5
  obj_weight: 1
  noobj_weight: 1
  wh_weight: 1
  landmark_weight: 3
  obj_thresh: 0.7
  iou_thresh: 0.5
train:
  dataset: voc
  augmenter: false
  batch_size: 16
  pre_ckpt: null
  rand_seed: 10101
  epochs: 10
  vail_split: 0.1
  log_dir: log
  debug: false
  verbose: 1
  optimizer: RAdam
  optimizer_kwarg:
    lr: 0.001
    beta_1: 0.9
    beta_2: 0.999
    epsilon: null
    decay: 0.0
  Lookahead: true
  Lookahead_kwarg:
    k: 5
    alpha: 0.5
prune:
  is_prune: false
  init_sparsity: 0.5
  final_sparsity: 0.9
  end_epoch: 5
  frequency: 100
