MIXED_PRECISION_DTYPE: &MIXED_PRECISION_DTYPE float32

mode: train
model:
  name: facdepix2pix
  helper: CMPFacadeHelper
  helper_kwarg:
    dataset_root: /home/zqh/workspace/facades
    in_hw: 
      - 256
      - 256
    mixed_precision_dtype: *MIXED_PRECISION_DTYPE
    hparams: null
  network: pix2pix_facde
  network_kwarg: null
train:
  graph_optimizer: true
  graph_optimizer_kwarg:
    layout_optimizer: true
    remapping: true
    shape_optimization: true
    loop_optimization: true
    constant_folding: true
    function_optimization: true
    scoped_allocator_optimization: true
  distributionstrategy_kwarg:
    tpu: null
    strategy: Mirrored
  augmenter: true
  batch_size: 16
  pre_ckpt: null
  rand_seed: 10101
  epochs: 100
  train_epoch_step: null
  vali_epoch_step: null
  steps_per_run: 5
  log_dir: log
  sub_log_dir: default_facde_pix2pix_exp
  mixed_precision:
    enable: false
    dtype: *MIXED_PRECISION_DTYPE
  trainloop: Pix2PixLoop
  trainloop_kwarg:
    hparams:
      wl1: 100 # generator loss = gan_loss + wl1 * l1_loss, in paper wl1 = 100. 
      # ema:
      #   enable: true
      #   decay: 0.999
  variablecheckpoint_kwarg:
    variable_dict:
      g_model: generator_model
      d_model: discriminator_optimizer
      g_optimizer: generator_optimizer
      d_optimizer: discriminator_optimizer
    monitor: train/g_loss
    mode: min
  generator_optimizer: Adam
  generator_optimizer_kwarg:
    learning_rate: 0.0002
    beta_1: 0.5
  discriminator_optimizer: Adam
  discriminator_optimizer_kwarg:
    learning_rate: 0.0002
    beta_1: 0.5
  callbacks:
    - name: EarlyStopping
      kwarg:
        monitor: train/g_loss
        min_delta: 0
        patience: 50
        verbose: 0
        mode: min
        baseline: null
        restore_best_weights: false
    # - name: ScheduleLR
    #   kwarg:
    #     base_lr: 0.03
    #     use_warmup: true
    #     warmup_epochs: 20
    #     decay_rate: 0.7
    #     decay_epochs: 20
    #     outside_optimizer: generator_optimizer
    # - name: ScheduleLR
    #   kwarg:
    #     base_lr: 0.03
    #     use_warmup: true
    #     warmup_epochs: 20
    #     decay_rate: 0.7
    #     decay_epochs: 20
    #     outside_optimizer: discriminator_optimizer
