mode: train
model:
  name: semiaudio
  helper: DCASETask2Helper
  helper_kwarg:
    image_ann: data/dcasetask5_img_ann.npy
    in_hw:
      - 128
      - 512
    fold: 0
  network: dualmbv2net
  network_kwarg:
    input_shape:
      - 128
      - 512
      - 1
    class_num: 80
    depth_multiplier: 1.0
  loss: SemiBCELoss
  loss_kwarg: null
train:
  graph_optimizer: true
  graph_optimizer_kwarg: 
    layout_optimizer: true
    remapping: true
    shape_optimization: true
    loop_optimization: true
    constant_folding: true
    function_optimization: true
    scoped_allocator_optimization: true
    layout_optimizer: true
  augmenter: true
  batch_size: 32
  pre_ckpt: null
  rand_seed: 10101
  epochs: 150
  log_dir: log
  sub_log_dir: default_dcasetask5_exp
  debug: false
  verbose: 1
  vali_step_factor: 0.3
  optimizer: Adam
  optimizer_kwarg:
    learning_rate: 0.001
    beta_1: 0.9
    beta_2: 0.999
    amsgrad: false
  Lookahead: false
  Lookahead_kwarg:
    k: 5
    alpha: 0.5
  callbacks:
    - name: EarlyStopping
      kwarg:
        monitor: val_lwlrap
        min_delta: 0
        patience: 30
        verbose: 0
        mode: max
        baseline: null
        restore_best_weights: false
    - name: ModelCheckpoint
      kwarg:
        monitor: val_lwlrap
        verbose: 0
        save_best_only: true
        save_weights_only: false
        mode: max
        save_freq: epoch
        load_weights_on_restart: false
    - name: LwlrapValidation
      kwarg: null
    - name: StepLR
      kwarg:
        steps: [ 50  ,  80    ,  120   ]
        rates: [0.0001, 0.0004,  0.0001]

prune:
  is_prune: false
  init_sparsity: 0.5
  final_sparsity: 0.9
  end_epoch: 5
  frequency: 100
inference:
  infer_fn: null
evaluate:
  eval_fn: null