mode: train
model:
  name: feacrec
  helper: FcaeRecHelper
  helper_kwarg:
    image_ann: data/celeba_facerec_img_ann.npy
    in_hw:
      - 96
      - 96
    embedding_size: 128
  network: mbv1_facerec
  network_kwarg:
    input_shape:
      - 96
      - 96
      - 3
    embedding_size: 128
    depth_multiplier: 1.0
  loss: Triplet_Loss
  loss_kwarg:
    alpha: 0.6
train:
  jit: true
  augmenter: false
  batch_size: 64
  pre_ckpt: null
  rand_seed: 10101
  epochs: 30
  log_dir: log
  debug: false
  verbose: 1
  vali_step_factor: 0.3
  optimizer: RAdam
  optimizer_kwarg:
    lr: 0.0005
    beta_1: 0.9
    beta_2: 0.999
    epsilon: null
    decay: 0.0
  Lookahead: true
  Lookahead_kwarg:
    k: 5
    alpha: 0.5
  earlystop: false
  earlystop_kwarg:
    monitor: val_loss
    min_delta: 0
    patience: 4
    verbose: 0
    mode: auto
    baseline: null
    restore_best_weights: false
  modelcheckpoint: true
  modelcheckpoint_kwarg:
    monitor: val_loss
    verbose: 0
    save_best_only: true
    save_weights_only: false
    mode: auto
    save_freq: epoch
    load_weights_on_restart: false
prune:
  is_prune: false
  init_sparsity: 0.5
  final_sparsity: 0.9
  end_epoch: 5
  frequency: 100
inference:
  infer_fn: pfld_infer
  infer_fn_kwarg:
    radius: 1
