mode: train
model:
  name: retinaface
  helper: RetinaFaceHelper
  helper_kwarg:
    image_ann: data/retinaface_img_ann.npy
    in_hw: 
      - 640
      - 640
    anchor_widths: 
      - 
        - 0.025
        - 0.05
      - 
        - 0.1
        - 0.2
      - 
        - 0.4
        - 0.8
    anchor_steps:
      - 8
      - 16
      - 32
    pos_thresh: 0.35
    variances:
      - 0.1
      - 0.2
  network: retinafacenet
  network_kwarg:
    input_shape:
      - 3
      - null
      - null
    anchor_num: 2
    filters: 64
    alpha: 0.25
  loss: RetinaFaceLoss
  loss_kwarg:
    negpos_ratio: 7
train:
  graph_optimizer: true
  graph_optimizer_kwarg: 
    layout_optimizer: true
    remapping: true
    shape_optimization: true
    loop_optimization: true
    constant_folding: true
    function_optimization: true
    scoped_allocator_optimization: true
    layout_optimizer: true
  augmenter: true
  batch_size: 16
  pre_ckpt: null
  rand_seed: 10101
  epochs: 150
  log_dir: log
  sub_log_dir: default_retinaface_exp
  debug: false
  verbose: 1
  vali_step_factor: 0.1
  optimizer: Adam
  optimizer_kwarg:
    learning_rate: 0.0001
    beta_1: 0.9
    beta_2: 0.999
    amsgrad: false
  Lookahead: true
  Lookahead_kwarg:
    k: 5
    alpha: 0.5
  callbacks:
    # - name: EarlyStopping
    #   kwarg:
    #     monitor: val_loss
    #     min_delta: 0
    #     patience: 4
    #     verbose: 0
    #     mode: auto
    #     baseline: null
    #     restore_best_weights: false
    - name: ModelCheckpoint
      kwarg:
        monitor: val_loss
        verbose: 0
        save_best_only: true
        save_weights_only: false
        mode: auto
        save_freq: epoch
        load_weights_on_restart: false
    - name: TerminateOnNaN
      kwarg: null
    # - name: MultiScaleTrain
    #   kwarg:
    #     interval: 50
    #     scale_range: [-3, 5]
    - name: StepLR
      kwarg:
        steps: [ 50  ,  80    ,  120 ]
        rates: [0.002, 0.001,  0.0001]
prune:
  is_prune: false
  init_sparsity: 0.5
  final_sparsity: 0.9
  end_epoch: 5
  frequency: 100
inference:
  infer_fn: yolo_infer
  infer_fn_kwarg:
    obj_thresh: 0.7
    iou_thresh: 0.3
evaluate:
  eval_fn: yolo_eval
  eval_fn_kwarg:
    det_obj_thresh: 0.1
    det_iou_thresh: 0.3
    mAp_iou_thresh: 0.3
    class_name:
      - aeroplane
      - bicycle
      - bird
      - boat
      - bottle
      - bus
      - car
      - cat
      - chair
      - cow
      - diningtable
      - dog
      - horse
      - motorbike
      - person
      - pottedplant
      - sheep
      - sofa
      - train
      - tvmonitor
    save_result: true
    save_result_dir: /home/zqh/Documents/mAP/input