mode: train
model:
  name: supervisedaudio
  helper: DCASETask5Helper
  helper_kwarg:
    image_ann: data/dcasetask5_ann_list.npy
    in_hw:
      - 40
      - 501
    nclasses: 9
  network: dcasetask5basemodel
  network_kwarg:
    input_shape:
      - 40
      - 501
      - 1
    nclasses: 9
    softmax: false
train:
  graph_optimizer: true
  graph_optimizer_kwarg: 
    layout_optimizer: true
    remapping: true
    shape_optimization: true
    loop_optimization: true
    constant_folding: true
    function_optimization: true
    scoped_allocator_optimization: true
    layout_optimizer: true
  augmenter: true
  batch_size: 32
  pre_ckpt: log/default_dcasetask5_exp/auto_train_19.h5
  rand_seed: 10101
  epochs: 50
  steps_per_run: 30
  log_dir: log
  sub_log_dir: default_dcasetask5_exp
  trainloop: Task5SupervisedLoop
  optimizer: Adam
  optimizer_kwarg:
    learning_rate: 0.001
    beta_1: 0.9
    beta_2: 0.999
    amsgrad: false
  callbacks:
    - name: EarlyStopping
      kwarg:
        monitor: val/acc
        min_delta: 0
        patience: 5
        verbose: 0
        mode: max
        baseline: null
        restore_best_weights: false
    - name: ModelCheckpoint
      kwarg:
        monitor: val/acc
        verbose: 0
        save_best_only: true
        save_weights_only: false
        mode: max
        save_freq: epoch
        load_weights_on_restart: false
    - name: StepLR
      kwarg:
        steps: [ 10  ,  20    ,  30   ]
        rates: [0.0001, 0.0004,  0.0005]
