BATCH_SIZE_REF: &BATCH_SIZE_REF 64
WIDTH_REF: &WIDTH_REF 112

mode: train
model:
  name: feacrec
  helper: FcaeRecHelper
  helper_kwarg:
    image_ann: data/ms1m_img_ann.npy
    in_hw:
      - *WIDTH_REF
      - *WIDTH_REF
    embedding_size: 128
    val_dataset: lfw,cfp_fp,agedb_30
    use_softmax: false
  network: mbv1_facerec_k210_eager
  network_kwarg:
    input_shape:
      - *WIDTH_REF
      - *WIDTH_REF
      - 3
    class_num: 85742
    embedding_size: 128
    depth_multiplier: 0.5
    loss: triplet
train:
  graph_optimizer: true
  graph_optimizer_kwarg: 
    layout_optimizer: true
    remapping: true
    shape_optimization: true
    loop_optimization: true
    constant_folding: true
    function_optimization: true
    scoped_allocator_optimization: true
    layout_optimizer: true
  augmenter: true
  batch_size: *BATCH_SIZE_REF
  pre_ckpt: log/default_facerec_triplet_k210_exp_backup/auto_train_58.h5
  rand_seed: 10101
  epochs: 100
  steps_per_run: 30
  log_dir: log
  sub_log_dir: default_facerec_triplet_k210_eager_exp
  mixed_precision:
    enable: false 
    dtype: float32
  trainloop: FaceTripletTrainingLoop
  trainloop_kwarg: 
    hparams:
      loss:
        target_distance: 1.0
        distance_fn: 'l2'
  variablecheckpoint_kwarg: 
    variable_dict:
      model: train_model
      optimizer: optimizer
    monitor: val/acc
    mode: max
  optimizer: Adam
  optimizer_kwarg:
    learning_rate: 0.001
    beta_1: 0.9
    beta_2: 0.999
    amsgrad: false
  callbacks:
    - name: EarlyStopping
      kwarg:
        monitor: val/acc
        min_delta: 0
        patience: 4
        verbose: 0
        mode: max
        baseline: null
        restore_best_weights: false
    - name: StepLR
      kwarg:
        steps: [ 50  ,  80    ,  120   ]
        rates: [0.0004, 0.0004,  0.0001]
