mode: train
model:
  name: yolo
  helper: YOLOAlignHelper
  helper_kwarg:
    image_ann: data/celeba_img_ann.npy
    class_num: 1
    anchors: data/celeba_anchor.npy
    landmark_num: 5
    in_hw:
      - 224
      - 320
    out_hw:
      - - 7
        - 10
      - - 14
        - 20
    validation_split: 0.1
  network: yoloalgin_mobilev1
  network_kwarg:
    landmark_num: 5
    alpha: 0.75
  loss: yoloalign_loss
  loss_kwarg:
    obj_thresh: 0.7
    iou_thresh: 0.5
    obj_weight: 1
    noobj_weight: 1
    wh_weight: 1
    landmark_weight: 2
train:
  augmenter: false
  batch_size: 16
  pre_ckpt: null
  rand_seed: 10101
  epochs: 10
  log_dir: log
  debug: false
  verbose: 1
  vali_step_factor: 0.5
  optimizer: RAdam
  optimizer_kwarg:
    lr: 0.001
    beta_1: 0.9
    beta_2: 0.999
    epsilon: null
    decay: 0.0
  Lookahead: true
  Lookahead_kwarg:
    k: 5
    alpha: 0.5
prune:
  is_prune: false
  init_sparsity: 0.5
  final_sparsity: 0.9
  end_epoch: 5
  frequency: 100
