mode: train
model:
  name: pfld
  helper: PFLDHelper
  helper_kwarg:
    image_ann: data/wflw_img_ann.npy
    in_hw:
      - 112
      - 112
    landmark_num: 98
    attribute_num: 6
    validation_split: 0.3
  network: pfld
  network_kwarg:
    input_shape:
    - 112
    - 112
    - 3
    landmark_num: 98
    alpha: 1.
    weight_decay: 0.00005
  loss: PFLD_Loss
  loss_kwarg:
    landmark_weight: 1.
    eular_weight: 1.
train:
  jit: true
  augmenter: false
  batch_size: 64
  pre_ckpt: null
  rand_seed: 10101
  epochs: 10
  log_dir: log
  sub_log_dir: null
  debug: false
  verbose: 1
  vali_step_factor: 0.5
  optimizer: RAdam
  optimizer_kwarg:
    lr: 0.001
    beta_1: 0.9
    beta_2: 0.999
    epsilon: null
    decay: 0.0
  Lookahead: true
  Lookahead_kwarg:
    k: 5
    alpha: 0.5
  earlystop: true
  earlystop_kwarg:
    monitor: val_loss
    min_delta: 0
    patience: 4
    verbose: 0
    mode: auto
    baseline: null
    restore_best_weights: false
  modelcheckpoint: true
  modelcheckpoint_kwarg:
    monitor: val_loss
    verbose: 0
    save_best_only: true
    save_weights_only: false
    mode: auto
    save_freq: epoch
    load_weights_on_restart: false
prune:
  is_prune: false
  init_sparsity: 0.5
  final_sparsity: 0.9
  end_epoch: 5
  frequency: 100
inference:
  infer_fn: pfld_infer
  infer_fn_kwarg:
    radius: 1
