mode: train
model:
  name: fixmatchaudio
  helper: DCASETask5FixMatchSSLHelper
  helper_kwarg:
    data_ann: data/dcasetask5_ann_list.npy
    in_hw:
      - 40
      - 501
    nclasses: 9
    unlabel_dataset_ratio: 3 # Unlabeled batch size ratio.
    augment_kwargs:
      name: randaugment
      kwarg: 
        num_layers: 3
        prob_to_apply: 0.5
        num_levels: 10
  network: dcasetask5basemodel
  network_kwarg:
    input_shape:
      - 40
      - 501
      - 1
    nclasses: 9
    softmax: false
    weight_decay: 0.0003
    bn_decay: 0.9
    bn_epsilon: 0.00001
train:
  graph_optimizer: true
  graph_optimizer_kwarg: 
    layout_optimizer: true
    remapping: true
    shape_optimization: true
    loop_optimization: true
    constant_folding: true
    function_optimization: true
    scoped_allocator_optimization: true
    layout_optimizer: true
  augmenter: true
  batch_size: 16
  pre_ckpt: null
  rand_seed: 10101
  epochs: 50
  steps_per_run: 30
  log_dir: log
  sub_log_dir: default_dcasetask5_fixmatch_randaug_exp
  mixed_precision:
    enable: false 
    dtype: float32
  trainloop: Task5FixMatchSslLoop
  trainloop_kwarg:
    hparams: 
      update_augmenter_state: false
      fixmatch: 
        wu: 1.0 # Pseudo label loss weight
        confidence: 0.7 # Confidence threshold.
      ema:
        enable: true
        decay: 0.999
  variablecheckpoint_kwarg: 
    variable_dict:
      model: train_model
      model_ema: val_model
      optimizer: optimizer
    monitor: val/acc
    mode: max
  optimizer: Adam
  optimizer_kwarg:
    learning_rate: 0.001
    beta_1: 0.9
    beta_2: 0.999
    amsgrad: false
  callbacks:
    - name: EarlyStopping
      kwarg:
        monitor: val/acc
        min_delta: 0
        patience: 5
        verbose: 0
        mode: max
        baseline: null
        restore_best_weights: false
    - name: ScheduleLR    
      kwarg:
       base_lr: 0.001
       use_warmup: true
       warmup_epochs: 10
       decay_rate: 0.5
       decay_epochs: 10
        
    