BATCH_SIZE_REF: &BATCH_SIZE_REF 64
WIDTH_REF: &WIDTH_REF 112

mode: train
model:
  name: feacrec
  helper: FcaeRecHelper
  helper_kwarg:
    image_ann: data/ms1m_img_ann.npy
    in_hw:
      - *WIDTH_REF
      - *WIDTH_REF
    embedding_size: 128
    use_softmax: false
  network: mbv1_facerec
  network_kwarg:
    input_shape:
      - *WIDTH_REF
      - *WIDTH_REF
      - 3
    class_num: 85742
    embedding_size: 128
    depth_multiplier: 0.5
    loss: triplet
  loss: TripletLoss
  loss_kwarg:
    target_distance: 3.9
    distance_fn: l2
train:
  graph_optimizer: true
  graph_optimizer_kwarg: 
    layout_optimizer: true
    remapping: true
    shape_optimization: true
    loop_optimization: true
    constant_folding: true
    function_optimization: true
    scoped_allocator_optimization: true
  augmenter: true
  batch_size: *BATCH_SIZE_REF
  pre_ckpt: null
  rand_seed: 10101
  epochs: 100
  log_dir: log
  sub_log_dir: default_facerec_triplet_exp
  debug: false
  verbose: 1
  vali_step_factor: 0.3
  optimizer: Adam
  optimizer_kwarg:
    learning_rate: 0.001
    beta_1: 0.9
    beta_2: 0.999
    amsgrad: false
  Lookahead: true
  Lookahead_kwarg:
    k: 5
    alpha: 0.5
  callbacks:
    - name: EarlyStopping
      kwarg:
        monitor: val_acc
        min_delta: 0
        patience: 4
        verbose: 0
        mode: max
        baseline: null
        restore_best_weights: false
    - name: ModelCheckpoint
      kwarg:
        monitor: val_acc
        verbose: 0
        save_best_only: true
        save_weights_only: false
        mode: max
        save_freq: epoch
        load_weights_on_restart: false
    - name: FacerecValidation
      kwarg:
        batch_size: *BATCH_SIZE_REF
        distance_fn: l2
        threshold: 0.1
    - name: StepLR
      kwarg:
        steps: [ 50  ,  80    ,  120   ]
        rates: [0.0001, 0.0004,  0.0001]

prune:
  is_prune: false
  init_sparsity: 0.5
  final_sparsity: 0.9
  end_epoch: 5
  frequency: 100
inference:
  infer_fn: null
evaluate:
  eval_fn: facerec_eval
  eval_fn_kwarg:
    nrof_folds: 5
    pca: 0
    batch_size: 64
    is_plot: true
